name: 'Shopware CLI Action'
description: 'GitHub Action for Shopware CLI, a command line tool helper for Shopware'
author: 'FriendsOfShopware'
branding:
  color: 'green'
  icon: 'package'

inputs:
  version:
    description: 'Shopware CLI version'
    default: 'latest'
    required: false
github-token:
    description: "GitHub Token used to authenticate against a repository for Git context"
    default: ${{ github.token }}
    required: false

runs:
  using: 'node20'
  main: 'dist/main/main.js'
  post: 'dist/post/main.js'
