name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Install Shopware CLI
        uses: ./.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test binary
        run: shopware-cli --version

      - name: Clone FroshTools
        run: git clone https://github.com/FriendsOfShopware/FroshTools.git

      - name: Zip FroshTools
        run: shopware-cli extension zip FroshTools

      - name: Validate
        run: shopware-cli extension validate FroshTools-*.zip
